"""add_user_verification_fields

Revision ID: 1d6bcb72526e
Revises: 251d4c53e59a
Create Date: 2026-08-10 05:50:43.365330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d6bcb72526e'
down_revision: Union[str, Sequence[str], None] = '251d4c53e59a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_gmail_verified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('is_tg_verified', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_tg_verified')
    op.drop_column('users', 'is_gmail_verified')
    # ### end Alembic commands ###
