"""update_products_and_create_users_products

Revision ID: c3991f01eeed
Revises: b6eef8ff4be0
Create Date: 2026-08-13 03:22:08.745690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3991f01eeed'
down_revision: Union[str, Sequence[str], None] = 'b6eef8ff4be0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('target_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_notification_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('target_price > 0', name='check_target_price_is_positive'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id', name='uq_user_product')
    )
    op.add_column('products', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('image_url', sa.Text(), nullable=True))
    op.drop_constraint(op.f('unique_id_url'), 'products', type_='unique')
    op.create_index(op.f('ix_products_url'), 'products', ['url'], unique=True)
    op.drop_constraint(op.f('products_user_id_fkey'), 'products', type_='foreignkey')
    op.drop_column('products', 'user_id')
    op.drop_column('products', 'target_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('target_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('products_user_id_fkey'), 'products', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_products_url'), table_name='products')
    op.create_unique_constraint(op.f('unique_id_url'), 'products', ['user_id', 'url'], postgresql_nulls_not_distinct=False)
    op.drop_column('products', 'image_url')
    op.drop_column('products', 'description')
    op.drop_table('users_products')
    # ### end Alembic commands ###
